# Generated by Django 5.2.12 on 2026-03-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='demo_balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, help_text='Virtual demo balance in USD.', max_digits=14),
        ),
        migrations.AddField(
            model_name='customuser',
            name='disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the demo account disclaimer.'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.DecimalField(decimal_places=6, max_digits=14)),
                ('avg_buy_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
