# Generated by Django 5.2.12 on 2026-03-13 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_customuser_demo_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('risk_profile', models.CharField(choices=[('aggressive', 'Aggressive'), ('conservative', 'Conservative')], default='aggressive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='RobotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('Buy', 'Buy'), ('Hold', 'Hold'), ('Sell', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('shares', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.robotsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot_trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
