# Generated by Django 5.2.12 on 2026-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_robotsession_robottrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotsession',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Total capital allocated to this robot session.', max_digits=14),
        ),
        migrations.AddField(
            model_name='robotsession',
            name='budget_remaining',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Cash portion of the budget not currently invested.', max_digits=14),
        ),
    ]
